Registercentrum/stratum-cms

templates/views/page.hbs

@rogsa Could you see if this is sufficient for now and in that case merge?

Added script tag which outputs the contents of advanced settings

---

templates/views/contact.hbs
templates/views/helpers/index.js
templates/views/index.hbs
templates/views/layouts/default.hbs
templates/views/news.hbs
templates/views/newsitem.hbs
templates/views/page.hbs
templates/views/partials/newswidget.hbs
templates/views/widgets/reportlist.hbs

Reverts Registercentrum/stratum-cms#45

Revert da36136e47360148c7fdacbf90300fce5a67d389

---

keystone.js
package.json
templates/views/contact.hbs
templates/views/helpers/index.js
templates/views/index.hbs
templates/views/layouts/default.hbs
templates/views/news.hbs
templates/views/newsitem.hbs
templates/views/page.hbs
templates/views/partials/newswidget.hbs
templates/views/widgets/reportlist.hbs

Cloudinary resources are loaded through https by default

44 bug force cloudinary https

---

keystone.js
models/StartPageWidget.js
public/styles/site.less
public/styles/site/jumbotron.less
public/styles/site/startpage-kicker.less
public/styles/site/variables.less
routes/views/index.js
templates/views/index.hbs
templates/views/layouts/default.hbs
updates/0.0.6-sample-statistics.js

50 widget container

---

package.json

Removed dependencies to react and babel

---

routes/api/stratum-proxy.js
routes/index.js
routes/proxies/stratum.js

60 add stratum proxy

---

models/StartPage.js
templates/views/index.hbs

64 startpage attributes

---

models/StartPage.js
public/styles/site/news-roll.less
routes/views/index.js
templates/views/index.hbs
templates/views/partials/newsroll.hbs
updates/0.0.7-startpage-to-markdown.js

65 startpage structure

---

routes/middleware.js
templates/views/index.hbs

73 remove news

---

models/Page/BasePage.js
public/styles/site.less
public/styles/site/base-page.less
public/styles/site/caption-ct.less
public/styles/site/layout.less
public/styles/site/mixins/white-well.less
public/styles/site/navs.less
templates/views/page.hbs
templates/views/widgets/reportlist.hbs

75 base page layout

---

public/styles/site/base-page.less
templates/views/page.hbs

Also added a line under headings if images doesn't exist

Added more padding to base page container

---

routes/index.js
routes/middleware.js

Hidden contact page and changed name on registration

---

keystone.js
models/Page/Page.js
models/Page/SubPage.js
public/styles/site/navs.less
routes/api/sub-page-count.js
routes/index.js
routes/views/page.js
templates/views/page.hbs
utils/sub-page-count.js

92 indicate sub pages

---

keystone.js
models/Page/BasePage.js
public/styles/site.less
public/styles/site/base-page.less
public/styles/site/navbar-big.less
public/styles/site/navbar.less
public/styles/site/navs.less
public/styles/site/type.less
public/styles/site/variables.less
templates/views/layouts/default.hbs
templates/views/page.hbs
updates/0.0.8-remove-page-layout-wide.js

94 right sub menu

---

models/Page/BasePage.js
public/styles/site/base-page.less
public/styles/site/layout.less
public/styles/site/widgets/report-list.less
templates/views/page.hbs
updates/0.0.9-move-extra-images.js

102 fixed images pages

---

keystone.js
models/Contact.js
models/Page/BasePage.js
models/User.js
public/styles/site/base-page.less
routes/views/contact.js
routes/views/page.js
templates/views/contact.hbs
templates/views/page.hbs

New Contact model added
Closes #108

108 contact model

---

public/styles/site/footer.less
public/styles/site/layout.less
templates/views/layouts/default.hbs

Closes #82
Also removed some unnecessary tags and selectors

Added sticky footer fix

---

templates/views/page.hbs

Also refactored the template and got rid of unnecessary tags
Closes #111

Fixed bug where extra images were hidden in mobile

---

public/styles/site/base-page.less

Added styling for img and table in base page

---

models/RegisterInformation.js
package.json

Removed dependency to underscore.string

---

templates/views/index.hbs

Fixes jumbotron layout in mobile

---

client/scripts/actions/actions.js
package.json
webpack.config.js
webpack.production.config.js

147 ie login object assign

---

templates/views/layouts/default.hbs

159 reintroduce advanced settings widget

---

models/Page/BasePage.js
templates/views/page.hbs

157 page lead text

---

models/StartPageWidget.js
templates/views/index.hbs

160 startpage widget link

---

public/styles/site.less
public/styles/site/error-page.less
routes/index.js
routes/middleware.js
routes/proxies/stratum.js
routes/views/menublock.js
routes/views/newsitem.js
routes/views/page.js
templates/views/errors/404.hbs
templates/views/errors/500.hbs

178 new 404 page

---

models/Page/BasePage.js
routes/views/content-types/faq.js
routes/views/page.js

180 question filter

---

web.config

Allows for lower level domains pointing to registers

---

keystone.js
models/NewsItem.js
models/Page/BasePage.js
models/Resource.js
package.json
public/styles/site.less
public/styles/site/resource-list.less
routes/views/newsitem.js
routes/views/page.js
templates/views/newsitem.hbs
templates/views/page.hbs
templates/views/partials/resourcelist.hbs

141 resource model

---

client/scripts/index.jsx
models/NewsItem.js
models/StartPage.js
public/styles/site/news-item.less
public/styles/site/news-list.less
public/styles/site/news-roll.less
public/styles/site/news-widget.less
public/styles/site/type.less
public/styles/site/variables.less
routes/views/index.js
routes/views/news.js
templates/views/helpers/index.js
templates/views/index.hbs
templates/views/news.hbs
templates/views/newsitem.hbs
templates/views/partials/newsroll.hbs
templates/views/partials/newswidget.hbs
templates/views/partials/pagination.hbs
templates/views/partials/resourcelist.hbs
updates/0.0.14-remove-brief-news.js
updates/0.0.15-image-layout-news.js

194 newsitem adjustments

---

client/scripts/actions/actions.js
client/scripts/containers/Login.jsx
client/scripts/reducers/login.js

Added missing checks for protocol

---

models/Question.js
routes/views/content-types/faq.js

Fixes bug where question category could be empty

---

models/Widget.js
public/styles/site/stratum-widget.less
templates/views/page.hbs
templates/views/partials/stratumwidget.hbs
templates/views/partials/widget.hbs
updates/0.0.16-widget-size.js

204 large widget

---

client/scripts/actions/login.js
client/scripts/components/SITHSLogin.jsx
models/Page/BasePage.js
models/Page/SubPage.js
public/styles/site/layout.less
public/styles/site/resource-list.less
routes/views/menublock.js
routes/views/page.js
templates/views/helpers/index.js
templates/views/news.hbs
templates/views/page.hbs
templates/views/partials/printbutton.hbs
templates/views/partials/resourcelist.hbs
updates/0.0.17-disable-contact-layout.js
updates/0.0.18-publish-pages.js
utils/sub-page-count.js

Closes #206 
Closes #207 
Closes #202 
Closes #151

206 minor fixes

---

keystone.js
models/RegisterInformation.js
models/Report.js
models/StartPage.js
models/StratumRegister.js
models/SubRegister.js
public/styles/site/jumbotron.less
public/styles/site/news-widget.less
public/styles/site/startpage.less
public/styles/site/sub-registers.less
routes/middleware.js
routes/views/index.js
templates/views/index.hbs
templates/views/layouts/default.hbs
templates/views/partials/informationblurb.hbs
templates/views/partials/jumbotron.hbs
updates/0.0.19-remove-sub-registers.js

211 fix layout for portals

---

routes/api/stratum-login.js
routes/index.js
routes/middleware.js
routes/views/logout.js

Also made som clean up of the session variables. Should now work under
IE
Closes #210

Gzipped responses are now handles by the context proxy

---

keystone.js

It should now be easier to structure multiple registers under the same
cloudinary account
Closes #219

Added prefix to cloudinary

---

models/StartPage.js
public/styles/site/news-widget.less
templates/views/partials/informationblurb.hbs
templates/views/partials/newswidget.hbs

217 information blurb fixes

---

keystone.js
models/Contact.js
models/NewsItem.js
models/Page/BasePage.js
models/Report.js
models/StartPage.js
models/User.js
public/styles/site/jumbotron.less
templates/views/newsitem.hbs
templates/views/partials/newswidget.hbs

218 jumbotron heading

---

client/scripts/actions/bankid.js
client/scripts/actions/context.js
client/scripts/actions/login.js
client/scripts/containers/App.jsx
client/scripts/containers/Context.jsx
client/scripts/index.jsx
client/scripts/reducers/context.js
package.json
routes/api/stratum-login.js

224 one context bug

---

web.config

Redirects all calls to https

---

client/scripts/actions/context.js
client/scripts/actions/login.js
client/scripts/components/TimeLeftDialog.jsx
client/scripts/containers/App.jsx
client/scripts/main.jsx
client/scripts/reducers/login.js

183 stratum polling

---

client/scripts/actions/context.js
client/scripts/actions/login.js
client/scripts/components/TopNav.jsx
client/scripts/components/User.jsx
client/scripts/containers/App.jsx
client/scripts/containers/Context.jsx
client/scripts/reducers/login.js
keystone.js
public/styles/site/navbar.less
routes/middleware.js

140 move register button

---

client/scripts/actions/login.js

Removed check against stratumid in cookie

---

web.config

Disabled devErrors and debuggingEnabled

---

client/scripts/components/User.jsx
client/scripts/containers/Context.jsx
public/styles/site/navbar.less

Changed layout and wording of initial login context

---

models/Contact.js
models/MenuBlock.js
models/NewsItem.js
models/Page/BasePage.js
models/Question.js
models/QuestionCategory.js
models/RegisterInformation.js
models/StartPage.js
models/StartPageWidget.js
models/Widget.js

Added track to all relevant models

---

client/scripts/actions/login.js
routes/proxies/stratum.js

240 change context ie

---

client/scripts/widgets/HNSBCI.jsx
client/scripts/widgets/HNSBChildrenNew.jsx
client/scripts/widgets/MYRPostTotal.jsx
client/scripts/widgets/RORHearingTest.jsx
client/scripts/widgets/RORSatInfo.jsx
client/scripts/widgets/SEPOps.jsx
client/scripts/widgets/index.js
client/scripts/widgets/widgets.json
models/StartPageWidget.js

Added all completed widgets with stratum apis

---

keystone.js
utils/keystone-widgets.js

Widget index is now read relative to ROOT

---

client/scripts/widgets/BOAAndel.jsx
client/scripts/widgets/BOAArtrosSkola.jsx
client/scripts/widgets/HNSBCI.jsx
client/scripts/widgets/HNSBChildrenNew.jsx
client/scripts/widgets/HNSVPirs.jsx
client/scripts/widgets/HNSVSign.jsx
client/scripts/widgets/MYRPostTotal.jsx
client/scripts/widgets/RORHearingTest.jsx
client/scripts/widgets/RORSatInfo.jsx
client/scripts/widgets/SEPOps.jsx

Changed all calls in keystone widgets

---

client/scripts/actions/login.js
client/scripts/containers/Context.jsx

Now calls assignProfileContexts and clears hashtag on change

---

keystone.js
routes/middleware.js
templates/views/layouts/default.hbs
templates/views/partials/analytics.hbs

Added new global for google analytics

---

templates/views/errors/404.hbs
templates/views/errors/500.hbs
templates/views/layouts/default.hbs
webpack.production.config.js

Added brand to vendor build

---

templates/views/partials/newswidget.hbs

Added dot to Läs mer

---

public/styles/site/news-item.less
templates/views/newsitem.hbs

Added margin to published-at

---

client/scripts/actions/bankid.js
client/scripts/components/InputPersonalNr.jsx
client/scripts/utils/personalNumber.js

Century is now also required. Current year is validated against
personalnumber as well.
Closes #254

Dash between last 4 is no longer invalid

---

client/scripts/actions/bankid.js

Should stop IE from caching
Closes #265

Added cachebuster timestamp to url

---

routes/proxies/stratum.js

Should fix the problem for POST, PUT and DELETE

---

routes/views/news.js

Added sort on publishedDate to aggregate function

---

models/StartPageWidget.js
public/styles/site/startpage.less
routes/views/index.js
templates/views/helpers/index.js
templates/views/partials/jumbotron.hbs
updates/0.0.20-enable-start-page-widgets.js

135 improve jumbotron

---

keystone.js
routes/middleware.js
templates/views/helpers/index.js
templates/views/layouts/default.hbs

Added BRAND_LONG global and reduced size of title

---

models/NewsItem.js
routes/views/news.js
routes/views/newsitem.js

281 future news block

---

models/Page/BasePage.js
routes/middleware.js
routes/views/menublock.js
routes/views/page.js

282 register permissions

---

models/Widget.js
templates/views/layouts/default.hbs

289 stratum widget query string

---

client/scripts/actions/messages.js
client/scripts/main.jsx

Added cookie domain to messages cookies

---

client/scripts/components/TimeLeftDialog.jsx
client/scripts/components/UnitList.jsx
client/scripts/containers/Context.jsx

294 register contex menu

---

client/scripts/actions/login.js
client/scripts/reducers/login.js

Check timeleft is only called when window is in focus

---

client/scripts/actions/login.js
client/scripts/components/SITHSLogin.jsx

302 assign card bug

---

client/scripts/actions/login.js
client/scripts/components/SITHSLogin.jsx

304 new text new card

---

client/scripts/widgets/FONOForbettring.jsx
client/scripts/widgets/FONOPatientenket.jsx
client/scripts/widgets/RORImproved.jsx
client/scripts/widgets/RORVentetid.jsx
client/scripts/widgets/index.js
client/scripts/widgets/widgets.json

306 fono ror widgets

---

client/scripts/actions/login.js

Bug is now fixed, tested and working in IE11 and Chrome
Closes #308

308 assign siths bug

---

.gitignore
models/Resource.js

If there is no Azure Cloud configuration variables Resource files will
be stored as LocalFile instead under `public/temp/...`.
Closes #318

Resources are now saved as local files when missing Azure

---

routes/proxies/stratum.js

Fixes problem with stratum not picking up calls when deleting
registrations
Closes #321

Delete calls are now piped as regular calls

---

client/scripts/actions/login.js
client/scripts/reducers/login.js
keystone.js
routes/api/stratum-login.js
routes/proxies/stratum.js

Added automatic login for demo environment

---

client/scripts/components/InternalLink.jsx
client/scripts/containers/Index.jsx
client/scripts/reducers/startPage.js
models/InternalLink.js
models/StartPage.js
public/styles/site.less
public/styles/site/internal-link.less
public/styles/site/jumbotron.less
public/styles/site/mixins/white-well.less
public/styles/site/variables.less
routes/api/start-page.js

137 internal links

---

routes/index.js
routes/proxies/stratum.js

329 refine stratum proxy

---

client/scripts/actions/breadcrumbs.js
client/scripts/components/ErrorPage.jsx
client/scripts/components/Menu.jsx
client/scripts/components/NewsLink.jsx
client/scripts/components/SubMenu.jsx
client/scripts/containers/Page.jsx
client/scripts/containers/PageLink.jsx
client/scripts/containers/RouterApp.jsx
client/scripts/routes.jsx
keystone.js
routes/index.js

Introduced new global boolean variable `REACT_SPA` which determines if the application should be run as a single page application.
[Finishes #138710117]

Split up react spa and regular

---

client/scripts/components/StratumWidget.jsx
client/scripts/containers/Page.jsx
models/Widget.js
public/styles/site/login.less
public/styles/site/news-list.less

Stratum widget advanced settings

---

routes/api/page.js

Adds missing imageDescription to query select

---

public/styles/site/base-page.less

remove the forced 100% width on images in pages

Bugfix images in widgets

---

client/scripts/main.jsx
templates/views/partials/jumbotron.hbs
templates/views/partials/widget.hbs

Properties are now loaded in the non spa version as well...

Fix for extra properties for keystone widgets
